import json
import re
import os
import html
import shutil
from pathlib import Path
from typing import Optional, Any, Dict, List, Tuple

def get_qe_prefix(self):
    return getattr(self, "qe_bin_prefix", None) or os.environ.get("QE_BIN_PREFIX", "")


def read_qe_cutoffs(in_path: str) -> Dict[str, str]:
    """Read ecutwfc/ecutrho out of a QE input, so later steps in the same run can
    be pinned to the values the SCF actually used."""
    out: Dict[str, str] = {}
    try:
        with open(in_path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return out
    for key in ("ecutwfc", "ecutrho"):
        m = re.search(rf"^[ \t]*{key}[ \t]*=[ \t]*([^,\s]+)", text, re.IGNORECASE | re.MULTILINE)
        if m:
            out[key] = m.group(1)
    return out


def _set_or_insert_control_key(text: str, key: str, value: str) -> str:
    """Set `key='value'` in the first namelist of a QE input, inserting the line
    if it isn't there.

    A plain regex substitution silently no-ops when the key is absent, which for
    `prefix` means QE falls back to its 'pwscf' default — fine on its own, but it
    breaks as soon as one step in a chain writes an explicit prefix and another
    doesn't. Inserting guarantees every step agrees.

    Post-processing inputs (bands.x, dos.x, ...) have no &control; their single
    namelist (&BANDS, &DOS, ...) is where prefix belongs, so we target whichever
    namelist opens first rather than hard-coding &control.
    """
    pattern = re.compile(
        rf"(^[ \t]*{re.escape(key)}[ \t]*=[ \t]*)(?:['\"]?)([^,'\"\n]*)(?:['\"]?)([ \t]*,?)[ \t]*$",
        re.IGNORECASE | re.MULTILINE,
    )
    if pattern.search(text):
        return pattern.sub(rf"\1'{value}'\3", text)

    # Not present — insert just after the first namelist opener.
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if re.match(r"^[ \t]*&\w+", line):
            indent = re.match(r"^[ \t]*", line).group(0) + "  "
            lines.insert(i + 1, f"{indent}{key} = '{value}',")
            return "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    return text

def patch_qe_input_file(
    in_path: str,
    *,
    new_pseudo_dir: Optional[str] = None,
    new_outdir: Optional[str] = None,
    new_prefix: Optional[str] = None,
    # Pseudopotential replacement policy (choose one or both; pp_map has higher priority):
    pp_dir: Optional[str] = None,          # replace the 3rd column .UPF file with pp_dir/original-filename
    pp_map: Optional[Dict[str, str]] = None,  # species name -> pseudopotential file path (absolute or relative)
    pp_dir_clean: Optional[bool] = False,
    force_new_step: bool = False,
    new_cutoffs: Optional[Dict[str, str]] = None,   # {"ecutwfc": "80", "ecutrho": "320"}
) -> None:
    """
    In-place modification of QE input file:
    1) Replace pseudo_dir/outdir/prefix values if provided.
    2) In ATOMIC_SPECIES block, replace the 3rd column (.UPF file):
       - with pp_dir/filename if pp_dir is given, or
       - with pp_map[species] if provided (pp_map has higher priority).
    """
    with open(in_path, "r", encoding="utf-8") as f:
        text = f.read()

    def _replace_key(text: str, key: str, value: str) -> str:
        # Match lines like  key = '...'  or  key='...'  or  key = ... (possibly ending with a comma)
        # Try to preserve trailing comments
        pattern = re.compile(
            rf"(^\s*{re.escape(key)}\s*=\s*)(?:['\"]?)([^,'\"\n]+)(?:['\"]?)(\s*,?\s*)(?=$)",
            re.IGNORECASE | re.MULTILINE
        )
        # If no match, try a more relaxed version (allowing trailing comments)
        if not pattern.search(text):
            pattern = re.compile(
                rf"(^\s*{re.escape(key)}\s*=\s*)(?:['\"]?)([^,'\"\n]+)(?:['\"]?)(\s*,?\s*)(?=.*$)",
                re.IGNORECASE | re.MULTILINE
            )
        return pattern.sub(rf"\1'{value}'\3", text)

    # Always force pseudo_dir to the config-resolved absolute path — the LLM
    # often writes a relative one like '../PseudoDojo/...' that breaks once
    # the run's cwd is nested deeper than a single layer.
    if new_pseudo_dir:
        text = _replace_key(text, "pseudo_dir", new_pseudo_dir)
    if new_outdir:
        text = _replace_key(text, "outdir", new_outdir)
    if force_new_step and re.search(r"(?mi)^\s*restart_mode\s*=", text):
        text = _replace_key(text, "restart_mode", "from_scratch")
    # Force a single prefix across every step of a run. QE chains steps through
    # <outdir>/<prefix>.save: nscf/bands read the SCF charge density from it, and
    # bands.x reads the bands run's wavefunctions from it. Each step's input is
    # generated by an independent LLM call that cannot know what prefix the
    # previous step picked, so leaving this to the model silently breaks the
    # chain (bands.x reads a stale or nonexistent .save and emits garbage).
    if new_prefix:
        text = _set_or_insert_control_key(text, "prefix", new_prefix)
    # Same reasoning as prefix: nscf/bands runs read the SCF charge density, so
    # their plane-wave cutoffs MUST match the SCF run that produced it. Each
    # step's input comes from an independent LLM call that cannot see the earlier
    # file, so asking the model to "reuse the same cutoffs" does not hold — it
    # drifts (e.g. ecutrho 320 -> 360 on the bands step). Pin them numerically.
    if new_cutoffs:
        for key, value in new_cutoffs.items():
            pattern = re.compile(
                rf"(^[ \t]*{re.escape(key)}[ \t]*=[ \t]*)([^,\s]+)",
                re.IGNORECASE | re.MULTILINE,
            )
            if pattern.search(text):
                text = pattern.sub(rf"\g<1>{value}", text)

    # Process ATOMIC_SPECIES block
    lines = text.splitlines()
    new_lines: List[str] = []
    in_species = False

    # Keywords indicating the end of ATOMIC_SPECIES block
    species_end_keys = re.compile(
        r"^\s*(ATOMIC_POSITIONS|K_POINTS|CELL_PARAMETERS|ATOMIC_FORCES|OCCUPATIONS|CONSTRAINTS|&\w+)\b",
        re.IGNORECASE
    )

    for raw in lines:
        line = raw
        if not in_species:
            if re.match(r"^\s*ATOMIC_SPECIES\b", line, re.IGNORECASE):
                in_species = True
                new_lines.append(line)
                continue
            else:
                new_lines.append(line)
                continue

        # Inside ATOMIC_SPECIES
        if not line.strip() or species_end_keys.match(line):
            in_species = False
            new_lines.append(line)
            continue

        # Preserve inline comments (after '#')
        parts = line.split("#", 1)
        body = parts[0].rstrip()
        comment = (" #"+parts[1]) if len(parts) == 2 else ""

        # Expected format: species mass pseudopotential
        tokens = body.split()
        if len(tokens) >= 3:
            species, mass, ppfile = tokens[:3]
            # Only modify .upf files
            if ppfile.lower().endswith(".upf"):
                new_pp = ppfile
                # Priority: pp_dir_clean > pp_map > pp_dir
                if pp_dir_clean:
                    new_pp = f"{species}.upf".lower()
                elif pp_map and species in pp_map:
                    new_pp = pp_map[species]
                elif pp_dir:
                    new_pp = os.path.join(pp_dir, os.path.basename(ppfile))
                # Rebuild line (preserve extra tokens if present)
                rest = " ".join(tokens[3:]) if len(tokens) > 3 else ""
                rebuilt = f"{species} {mass} {new_pp}"
                if rest:
                    rebuilt += " " + rest
                line = rebuilt + comment
            else:
                line = body + comment
        else:
            line = raw

        new_lines.append(line)

    new_text = "\n".join(new_lines)
    if new_text != text:
        with open(in_path, "w", encoding="utf-8") as f:
            f.write(new_text)


def validate_pseudos_exist(in_path: str) -> Tuple[None, Optional[str]]:
    """Scan a QE input file's ATOMIC_SPECIES block and check that each
    referenced .upf exists under the file's pseudo_dir.

    Catches the (otherwise obscure) "rc=132 / mpirun cannot exec" failure
    when the selected pseudo library doesn't ship the element the LLM
    asked for (e.g. requesting Eu/Nd against PBE_standard which stops at
    Lu). Returns (None, "<error message>") on missing files so the agent
    can retry with different params instead of crashing pw.x.
    """
    try:
        with open(in_path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError as e:
        return None, f"could not read input file: {e}"

    pd_match = re.search(
        r"^\s*pseudo_dir\s*=\s*['\"]([^'\"]+)['\"]",
        text,
        re.IGNORECASE | re.MULTILINE,
    )
    if not pd_match:
        return None, None  # nothing to validate
    pseudo_dir = pd_match.group(1)
    if not os.path.isdir(pseudo_dir):
        return None, f"pseudo_dir does not exist on disk: {pseudo_dir}"

    species_end_keys = re.compile(
        r"^\s*(ATOMIC_POSITIONS|K_POINTS|CELL_PARAMETERS|ATOMIC_FORCES|OCCUPATIONS|CONSTRAINTS|&\w+)\b",
        re.IGNORECASE,
    )
    in_species = False
    missing: List[str] = []
    for raw in text.splitlines():
        if not in_species:
            if re.match(r"^\s*ATOMIC_SPECIES\b", raw, re.IGNORECASE):
                in_species = True
            continue
        if not raw.strip() or species_end_keys.match(raw):
            break
        body = raw.split("#", 1)[0].strip()
        tokens = body.split()
        if len(tokens) < 3:
            continue
        ppfile = tokens[2]
        if not ppfile.lower().endswith(".upf"):
            continue
        candidate = ppfile if os.path.isabs(ppfile) else os.path.join(pseudo_dir, ppfile)
        if not os.path.isfile(candidate):
            missing.append(ppfile)

    if missing:
        return None, (
            f"pseudopotential(s) not found in {pseudo_dir}: {', '.join(missing)}. "
            f"The selected library does not cover one of the requested elements."
        )
    return None, None


def package_pseudos_for_remote(
    input_paths: List[str],
    *,
    pseudo_dir: str,
    work_dir: str,
    package_dir_name: str = "pseudos",
) -> List[str]:
    """
    Copy only the pseudopotentials referenced by generated QE inputs into the
    run directory and patch inputs to use a relative pseudo_dir.

    Cluster jobs cannot see absolute paths from the local desktop, so remote
    packages must be self-contained:

        run_dir/input_*.in
        run_dir/slurm_job_*.sh
        run_dir/pseudos/*.upf
    """
    package_dir = Path(work_dir) / package_dir_name
    package_dir.mkdir(parents=True, exist_ok=True)

    copied: List[str] = []
    for input_path in input_paths:
        for pp_name in _qe_input_pseudo_filenames(input_path):
            src = Path(pp_name)
            if not src.is_absolute():
                src = Path(pseudo_dir) / pp_name
            if not src.is_file():
                raise FileNotFoundError(f"Could not package pseudopotential: {src}")
            dest = package_dir / src.name
            if not dest.exists():
                shutil.copy2(src, dest)
                copied.append(str(dest))

        patch_qe_input_file(
            input_path,
            new_pseudo_dir=f"./{package_dir_name}",
            pp_dir_clean=True,
        )

    return copied


def _qe_input_pseudo_filenames(in_path: str) -> List[str]:
    with open(in_path, "r", encoding="utf-8") as f:
        text = f.read()

    species_end_keys = re.compile(
        r"^\s*(ATOMIC_POSITIONS|K_POINTS|CELL_PARAMETERS|ATOMIC_FORCES|OCCUPATIONS|CONSTRAINTS|&\w+)\b",
        re.IGNORECASE,
    )
    in_species = False
    pp_files: List[str] = []
    for raw in text.splitlines():
        if not in_species:
            if re.match(r"^\s*ATOMIC_SPECIES\b", raw, re.IGNORECASE):
                in_species = True
            continue
        if not raw.strip() or species_end_keys.match(raw):
            break
        tokens = raw.split("#", 1)[0].strip().split()
        if len(tokens) >= 3 and tokens[2].lower().endswith(".upf"):
            pp_files.append(os.path.basename(tokens[2]))
    return pp_files


def normalize_qe_input_text(text: str) -> str:
    """Remove transport/markup escaping without changing QE semantics."""
    value = str(text or "").strip()
    # LLM and web transports sometimes wrap plain inputs as a Markdown block
    # or XML CDATA section. These wrappers are never valid QE syntax.
    fence = re.fullmatch(r"```(?:[a-zA-Z0-9_-]+)?\s*(.*?)\s*```", value, re.DOTALL)
    if fence:
        value = fence.group(1).strip()
    cdata = re.fullmatch(r"<!\[CDATA\[(.*?)\]\]>", value, re.DOTALL)
    if cdata:
        value = cdata.group(1).strip()
    # Decode twice at most so doubly escaped '&amp;amp;control' is repaired,
    # while avoiding an unbounded transformation loop.
    for _ in range(2):
        decoded = html.unescape(value)
        if decoded == value:
            break
        value = decoded
    return value.strip()


def parse_scripts_block(generated: str) -> list[str]:
    # Prefer explicit <script>...</script> tags when the model follows the
    # prompt exactly.
    scripts = re.findall(
        r"<script>(.*?)</script>|<script>(.*?)<\\script>",
        generated,
        flags=re.DOTALL | re.IGNORECASE,
    )

    # normalize
    normalized = [(s[0] if s[0] else s[1]).strip() for s in scripts]

    if not normalized:
        normalized = _fallback_script_blocks(normalize_qe_input_text(generated))

    normalized = [normalize_qe_input_text(s.replace("\\n", "\n")) for s in normalized]

    return normalized


def _fallback_script_blocks(generated: str) -> list[str]:
    text = (generated or "").strip()
    if not text:
        raise ValueError("No <script>...</script> blocks found in model output.")

    fence_matches = re.findall(r"```(?:[a-zA-Z0-9_-]+)?\s*(.*?)```", text, flags=re.DOTALL)
    candidates = [_extract_qe_input_region(m) for m in fence_matches]
    candidates = [c for c in candidates if c]
    if candidates:
        return candidates

    json_candidates = _extract_qe_inputs_from_json(text)
    if json_candidates:
        return json_candidates

    unescaped = text.replace("\\n", "\n").replace('\\"', '"')
    extracted = _extract_qe_input_region(unescaped)
    if extracted:
        return [extracted]

    raise ValueError("No <script>...</script> blocks found in model output.")


def _looks_like_qe_input(text: str) -> bool:
    return bool(
        re.search(r"(?mi)^\s*&(?:control|system|electrons|ions|cell|inputpp|input|dos|bands)\b", text)
        or re.search(r"(?mi)^\s*(ATOMIC_SPECIES|K_POINTS|ATOMIC_POSITIONS)\b", text)
    )


def _extract_qe_inputs_from_json(text: str) -> list[str]:
    try:
        obj = json.loads(text)
    except Exception:
        return []

    found: list[str] = []

    def visit(value: Any) -> None:
        if isinstance(value, str):
            extracted = _extract_qe_input_region(value.replace("\\n", "\n").replace('\\"', '"'))
            if extracted:
                found.append(extracted)
        elif isinstance(value, list):
            for item in value:
                visit(item)
        elif isinstance(value, dict):
            for item in value.values():
                visit(item)

    visit(obj)
    return found


def _extract_qe_input_region(text: str) -> Optional[str]:
    if not text:
        return None

    marker = re.search(
        r"(?mi)^\s*(?:&(?:control|system|electrons|ions|cell|inputpp|input|inputph|dos|bands|projwfc)\b|"
        r"ATOMIC_SPECIES\b|ATOMIC_POSITIONS\b|K_POINTS\b)",
        text,
    )
    if not marker:
        return None

    candidate = text[marker.start():].strip()
    candidate = re.split(r"(?mi)^\s*(?:</?scripts?>|</?script>|```)\s*$", candidate)[0].strip()
    if _looks_like_qe_input(candidate):
        return candidate
    return None


def write_inputs(
    work_dir: str,
    scripts: list,
    prefix: str = "input",
    suffix: str = ".in",
    subproblem_id: Optional[int] = None,
):
    """
    write multiple input scripts to files in work_dir.
    """
    os.makedirs(work_dir, exist_ok=True)
    paths = []
    for idx, content in enumerate(scripts, start=1):
        content = normalize_qe_input_text(content)
        if subproblem_id is None:
            filename = f"{prefix}_{idx}{suffix}"
        else:
            filename = f"{prefix}_{subproblem_id}_{idx}{suffix}"
        path = os.path.join(work_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content.rstrip() + "\n\n")
        paths.append(path)
    return paths

def parse_output_template(output_text: str):
    """
    Placeholder for output parsing rules.
    Extend this function to extract structured data from QE outputs.
    """
    return output_text, {}


# Cap how much pw.x output we feed to the LLM result-parser. gpt-4o has a
# 128K-token context; ~80KB of trimmed pw.x output is well under that even
# after the prompt's own boilerplate, but big enough to keep the final
# convergence block + JOB DONE banner that result_parse keys on.
_OUTPUT_TEXT_MAX_BYTES = 80_000
_OUTPUT_TEXT_HEAD_BYTES = 20_000  # keep the system-info header
_OUTPUT_TEXT_TAIL_BYTES = _OUTPUT_TEXT_MAX_BYTES - _OUTPUT_TEXT_HEAD_BYTES


def _cap_output_text(text: str) -> tuple[str, bool]:
    """Truncate huge pw.x outputs to keep the LLM prompt under context limits.

    Returns (capped_text, did_truncate). When truncated, the middle is
    elided with an explicit marker so the parser can tell the file was
    long but still has the start (params) and end (JOB DONE + results).
    """
    if len(text) <= _OUTPUT_TEXT_MAX_BYTES:
        return text, False
    head = text[:_OUTPUT_TEXT_HEAD_BYTES]
    tail = text[-_OUTPUT_TEXT_TAIL_BYTES:]
    elided = len(text) - len(head) - len(tail)
    marker = f"\n\n... [{elided} bytes elided to fit LLM context — middle of output dropped] ...\n\n"
    return head + marker + tail, True


def preprocess_output_list(output_list: List[str], verbose: bool = False) -> List[str]:
    processed = []
    for idx, item in enumerate(output_list, start=1):
        text = _read_output_item(item)
        text, r1 = _strip_bands_blocks(text)

        # vc-relax: keep forces; scf/nscf/bands: forces usually can be dropped
        text, r2 = _strip_scf_iteration_noise(text, keep_forces_block=True)

        text, capped = _cap_output_text(text)

        # Trimming counts are internal bookkeeping for fitting the output into the
        # model's context — they mean nothing to the user watching the run, so they
        # stay out of the streamed log.
        processed.append(text)
    return processed

def _read_output_item(item: str) -> str:
    try:
        if os.path.exists(item):
            with open(item, "r", encoding="utf-8") as f:
                return f.read()
    except OSError:
        pass
    return item or ""


def _strip_bands_blocks(text: str) -> tuple[str, int]:
    lines = text.splitlines()
    cleaned: List[str] = []
    removed = 0
    idx = 0
    header_pattern = re.compile(r"^\s*k\s*=.*bands\s*\(ev\)\s*:?\s*$", re.IGNORECASE)
    while idx < len(lines):
        line = lines[idx]
        if header_pattern.match(line):
            removed += 1
            idx += 1
            while idx < len(lines) and (_is_blank_line(lines[idx]) or _is_numeric_line(lines[idx])):
                removed += 1
                idx += 1
            continue
        cleaned.append(line)
        idx += 1
    return "\n".join(cleaned), removed

def _strip_scf_iteration_blocks(text: str) -> tuple[str, int]:
    lines = text.splitlines()
    cleaned = []
    removed = 0
    idx = 0

    # 一组明确可删的 SCF / diagonalization 噪声模式
    drop_start_patterns = [
        re.compile(r"^\s*iteration\s*#\s*\d+", re.IGNORECASE),
        re.compile(r"^\s*Davidson diagonalization", re.IGNORECASE),
    ]

    drop_single_line_patterns = [
        re.compile(r"^\s*ethr\s*=", re.IGNORECASE),
        re.compile(r"^\s*total cpu time", re.IGNORECASE),
        re.compile(r"^\s*avg # of iterations", re.IGNORECASE),
    ]

    while idx < len(lines):
        line = lines[idx]

        # block start（iteration / Davidson）
        if any(p.match(line) for p in drop_start_patterns):
            removed += 1
            idx += 1
            # 吃掉后续的空行或数值行
            while idx < len(lines) and (
                _is_blank_line(lines[idx]) or
                _is_numeric_line(lines[idx])
            ):
                removed += 1
                idx += 1
            continue

        # 单行噪声
        if any(p.match(line) for p in drop_single_line_patterns):
            removed += 1
            idx += 1
            continue

        cleaned.append(line)
        idx += 1

    return "\n".join(cleaned), removed

def _strip_scf_iteration_noise(text: str, keep_forces_block: bool = True) -> Tuple[str, int]:
    lines = text.splitlines()
    cleaned: List[str] = []
    removed = 0
    i = 0

    iter_start = re.compile(r"^\s*iteration\s*#\s*\d+\b", re.IGNORECASE)

    # 这几类我们要“整块删除”
    # 从 iteration # N 开始，一直删到下一个 iteration # 或 “End of self-consistent calculation”
    scf_end = re.compile(r"^\s*End of self-consistent calculation\b", re.IGNORECASE)

    # 只保留最终 summary 里带 "!" 的 total energy（QE 的最终能量行）
    mid_total_energy = re.compile(r"^\s*total energy\s*=\s*", re.IGNORECASE)
    final_total_energy = re.compile(r"^\s*!\s*total energy\s*=\s*", re.IGNORECASE)

    # 这些行也经常巨大但对 parse 没用（你可以按需扩）
    drop_single = [
        re.compile(r"^\s*total cpu time spent up to now\b", re.IGNORECASE),
        re.compile(r"^\s*Davidson diagonalization\b", re.IGNORECASE),
        re.compile(r"^\s*ethr\s*=", re.IGNORECASE),
        re.compile(r"^\s*estimated scf accuracy\s*<\s*", re.IGNORECASE),  # 可选：只保留最终一次的话更复杂，这里先全删
    ]

    forces_header = re.compile(r"^\s*Forces acting on atoms\b", re.IGNORECASE)
    forces_end = re.compile(r"^\s*Total force\s*=", re.IGNORECASE)

    while i < len(lines):
        line = lines[i]

        # 1) 删除 iteration 块：从 iteration # 开始一直删到下一个 iteration 或 scf_end
        if iter_start.match(line):
            # drop until next iter_start or scf_end
            removed += 1
            i += 1
            while i < len(lines) and (not iter_start.match(lines[i])) and (not scf_end.match(lines[i])):
                removed += 1
                i += 1
            continue

        # 2) forces block：vc-relax 通常需要保留；scf/nscf/bands 可以关掉
        if forces_header.match(line):
            if keep_forces_block:
                cleaned.append(line)
                i += 1
                while i < len(lines):
                    cleaned.append(lines[i])
                    if forces_end.match(lines[i]):
                        break
                    i += 1
                i += 1
                continue
            else:
                removed += 1
                i += 1
                while i < len(lines):
                    removed += 1
                    if forces_end.match(lines[i]):
                        i += 1
                        break
                    i += 1
                continue

        # 3) 删除“中间 total energy = ...”（只保留带 ! 的最终能量）
        if mid_total_energy.match(line) and (not final_total_energy.match(line)):
            removed += 1
            i += 1
            continue

        # 4) 删除单行噪声
        if any(p.match(line) for p in drop_single):
            removed += 1
            i += 1
            continue

        cleaned.append(line)
        i += 1

    return "\n".join(cleaned), removed


def _is_blank_line(line: str) -> bool:
    return not line.strip()


def _is_numeric_line(line: str) -> bool:
    numeric_pattern = re.compile(
        r"^\s*[-+]?(\d+(\.\d*)?|\.\d+)([eEdD][-+]?\d+)?(\s+[-+]?(\d+(\.\d*)?|\.\d+)([eEdD][-+]?\d+)?)*\s*$"
    )
    return bool(numeric_pattern.match(line))


def get_qe_result(
    work_dir: str,
    input_paths: list,
    verbose: bool = False,
    subproblem_id: Optional[int] = None,
    output_paths: Optional[list] = None,
) -> list:
    input_text = []
    output_text = []
    for idx, in_path in enumerate(input_paths, start=1):
        if output_paths and idx <= len(output_paths):
            out_path = output_paths[idx - 1]
        elif subproblem_id is None:
            out_path = os.path.join(work_dir, f"output_{idx}.out")
        else:
            out_path = os.path.join(work_dir, f"output_{subproblem_id}_{idx}.out")

        # Read the input file
        try:
            with open(in_path, "r", encoding="utf-8") as f:
                input_text.append(f.read())
        except FileNotFoundError:   
            if verbose:
                print(f"[parser] Input file not found: {in_path}")
            input_text.append("")
        
        # Read the output file
        try:
            with open(out_path, "r", encoding="utf-8") as f:
                raw_output = f.read()
                parsed_output, _ = parse_output_template(raw_output)
                output_text.append(parsed_output)
        except FileNotFoundError:   
            if verbose:
                print(f"[parser] Output file not found: {out_path}")
            output_text.append("")
    
    return input_text, output_text

def parse_plan_string(s: str) -> List[Dict[str, Any]]:
    """
    Parse a plan string containing <subproblemN>...</subproblemN> blocks.
    Each block must explicitly include lines starting with:
    Problem:, Tool:, Required input:. ``Why:`` and ``Sweep:`` are optional
    for compatibility with plans generated by older models.
    
    Returns a list of dicts with keys: id, problem, tool, input, why, sweep.
    """
    subproblems = []
    pattern = re.compile(r"<subproblem(\d+)>(.*?)</subproblem\1>", re.DOTALL | re.IGNORECASE)

    for match in pattern.finditer(s):
        pid = int(match.group(1))
        body = match.group(2).strip()
        lines = [line.strip() for line in body.splitlines() if line.strip()]

        # Defaults
        problem, tool, req_input, why, sweep = None, None, None, None, None

        for line in lines:
            if line.lower().startswith("problem:"):
                problem = line.split(":", 1)[1].strip()
            elif line.lower().startswith("tool:"):
                tool = line.split(":", 1)[1].strip()
            elif line.lower().startswith("required input:"):
                req_input = line.split(":", 1)[1].strip()
            elif line.lower().startswith("why:"):
                why = line.split(":", 1)[1].strip()
            elif line.lower().startswith("sweep:"):
                sweep = line.split(":", 1)[1].strip()

        subproblems.append({
            "id": pid,
            "problem": problem,
            "tool": tool,
            "input": req_input,
            "why": why,
            "sweep": sweep
        })

    if not subproblems:
        raise ValueError("No <subproblem> blocks found in input string")

    return subproblems

def extract_json_brutal(s: str):
    """
    get json structure
    """
    start = s.find("{")
    end = s.rfind("}")
    if start == -1 or end == -1 or start >= end:
        raise ValueError(f"No json structure in {s}")
    return json.loads(s[start:end+1])

def output_to_log_file(work_dir: str, file_name: str, output: str, new: bool = False):
    os.makedirs(work_dir, exist_ok=True)
    log_path = os.path.join(work_dir, file_name)
    mode = "w" if new else "a"
    with open(log_path, mode, encoding="utf-8") as f:
        f.write(output)
        if not output.endswith("\n"):
            f.write("\n")

def parse_test():
    test_str = '''### Answer:
    ```json
    {
    "question": "Calculate the band structure of silicon (fcc + 2 atoms basis, lattice constant = 5.43) along high-symmetry paths.",
    "work_dir": "jobs/si-fcc-bands/",
    "subproblems": [
        {
        "subquestion": "SCF to converge charge density (structure provided in question)",
        "call": {
            "tool": "quantum espresso",
            "fn": "pw_scf",
            "args": {
            "structure": { "lattice": "fcc", "a0": 5.43, "ibrav": 0, "species": ["Si"], "basis": ["Si"] },
            "ecutwfc": 40,
            "ecutrho": 320,
            "kpoints": [8,8,8],
            "occupations": "fixed",
            "conv_thr": 1e-6
            }
        }
        },
        {
        "subquestion": "NSCF along high-symmetry path",
        "call": {
            "tool": "quantum espresso",
            "fn": "pw_nscf",
            "args": {
            "structure_from": "pw_scf",
            "kpath": "seekpath:auto",
            "kpath_points": 200,
            "occupations": "fixed"
            }
        }
        },
        {
        "subquestion": "Postprocess band structure",
        "call": {
            "tool": "quantum espresso",
            "fn": "bands_post",
            "args": { "input_from": "pw_nscf", "plot": true }
        }
        }
    ],
    "notes": "Structure came from the question; SCF → NSCF (k-path) → bands.x post."
    }
    ```'''
    print(parse_plan_string(test_str))

    test_str = """    <scripts>
    <script>
    &control
    calculation = 'bands'
    restart_mode = 'from_scratch'
    prefix = 'X_fcc_a4p00_k12p00p12_e100'
    outdir = './out/'
    pseudo_dir = './pseudo/'
    /
    &system
    ibrav = 2
    celldm(1) = 4.00
    nat = 1
    ntyp = 1
    ecutwfc = 100
    /
    &electrons
    diagonalization = 'david'
    mixing_beta = 0.7
    /
    ATOMIC_SPECIES
    X  1.0  X.pbe.UPF
    ATOMIC_POSITIONS
    X  0.0  0.0  0.0
    K_POINTS
    automatic
    12  12  12  0  0  0
    </script>
    <script>
    &control
    calculation = 'bands'
    restart_mode = 'from_scratch'
    prefix = 'X_fcc_a4p00_k8p00p8p8_e100'
    outdir = './out/'
    pseudo_dir = './pseudo/'
    /
    &system
    ibrav = 2
    celldm(1) = 4.00
    nat = 1
    ntyp = 1
    ecutwfc = 100
    /
    &electrons
    diagonalization = 'david'
    mixing_beta = 0.7
    /
    ATOMIC_SPECIES
    X  1.0  X.pbe.UPF
    ATOMIC_POSITIONS
    X  0.0  0.0  0.0
    K_POINTS
    automatic
    8  8  8  0  0  0
    </script>
    <script>
    &control
    calculation = 'bands'
    restart_mode = 'from_scratch'
    prefix = 'X_fcc_a4p00_k10p00p10p10_e100'
    outdir = './out/'
    pseudo_dir = './pseudo/'
    /
    &system
    ibrav = 2
    celldm(1) = 4.00
    nat = 1
    ntyp = 1
    ecutwfc = 100
    /
    &electrons
    diagonalization = 'david'
    mixing_beta = 0.7
    /
    ATOMIC_SPECIES
    X  1.0  X.pbe.UPF
    ATOMIC_POSITIONS
    X  0.0  0.0  0.0
    K_POINTS
    automatic
    10  10  10  0  0  0
    </script>
    </scripts>"""

    ret = parse_scripts_block(generated = test_str)

    patch_qe_input_file("/workspace/DFTagent/test/job_pw.x_20250908_043840/input_1.in",
    new_pseudo_dir="/workspace/DFTagent/SSSP/",
    new_outdir="./tmp",
    new_prefix="scf_1",
    pp_dir="Si.pbe-n-rrkjus_psl.1.0.0.UPF"
    )

if __name__ == "__main__":
    parse_test()
